### ISSUE TITLE
Unable to calculate one 95% CI limit

### ISSUE THREAD

**Issue by joannadiong** [mayamathur/evalue#18]
Hi there,

Thanks for a cool package!

I am computing an E-value for a continuous outcome and a continuous exposure, using data from two cohorts. For each cohort, the program is able to estimate the E-value, but is unable to calculate one of the limits of the 95% CI. It prints "NA" for the upper limit of one cohort, and "NA" for the lower limit of the other cohort. 

I'm wondering whether this behaviour is because the E-value is an approximation when an outcome is continuous? Do you know how it could be resolved?

If it can't be resolved, in this instance, would it be better to simply report the E-value estimate in the paper without the CI, or report that the program was not able to calculate the one of the bounds of the CI?

Many thanks

**Comment by mayamathur** [comment]
The E-value for the CI only applies to the CI limit closer to the null.
